### ISSUE TITLE
Biotech mech gestation breaking

### ISSUE THREAD

**Issue by sdfsdfd2231** [bbradson/Performance-Fish#1]
With this mod active, trying to make almost any mechanoid thing at a gestator breaks and says you do not have the materials even if you do have the materials.
![image](https://user-images.githubusercontent.com/104033415/198379188-21a32ced-fd90-4dde-83ee-e2cad4689053.png)
This was resolved instantly when i removed performance fish. No errors appeared in the log but i can reproduce and get any info if requested. I have none of the listed incompatible mods.

**Comment by bbradson** [comment]
Thanks. I pushed a fix for this now.
