### ISSUE TITLE
error prepachter

### ISSUE THREAD

**Issue by raulcorso** [bbradson/Performance-Fish#11]
does not start error in prepachter version steam

installed mods:
performance fish
prepachter
fishery
harmony

Prepatcher Error: Exception while reloading: System.NullReferenceException: Settings refonly on a null assembly
  at Prepatcher.UnsafeAssembly.SetReflectionOnly (System.Reflection.Assembly asm, System.Boolean value) [0x00017] in <2bd5fe90b5e247b7b0a9606776d93baa>:0 
  at Prepatcher.Process.ModifiableAssembly.SetSourceRefOnly () [0x0001b] in <2bd5fe90b5e247b7b0a9606776d93baa>:0 
  at Prepatcher.Process.Reloader.Reload (Prepatcher.Process.AssemblySet set, System.Action`1[T] loadAssemblyAction) [0x000b8] in <2bd5fe90b5e247b7b0a9606776d93baa>:0 
  at Prepatcher.Process.GameProcessing.Process () [0x00153] in <2bd5fe90b5e247b7b0a9606776d93baa>:0 
  at Prepatcher.Loader.Reload () [0x0009a] in <2bd5fe90b5e247b7b0a9606776d93baa>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
Prepatcher.PrepatcherMod/<>c:<InitLg>b__6_1 (object)
Prepatcher.Lg:Error (string)
Prepatcher.Loader:Reload ()
Prestarter.ModManager:<Launch>b__59_0 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by bbradson** [comment]
Well, it certainly should start in a list of only those mods. I can't predict for sure what exactly went wrong for you, but I can try listing a couple of possible causes I could think of. Prepatcher has to be updated to the newest version, and that version is only available on Steam. Its GitHub code view only contains sources and its releases section is outdated. If you did get it from Steam, try deleting its folder and forcing a redownload by unsubscribing and resubscribing. The load order is important too. Prepatcher has to be loaded first, followed by Harmony, Fishery, Core, Performance Fish, DLCs, and other mods after. RimWorld should be updated to 1.4.3704. If you've included more mods it's theoretically possible that one of them is incompatible with Prepatcher too. You'd have to find that mod through trial and error then.

**Comment by raulcorso** [comment]
Apparently it's a problem only with Prepatcher, so I'm going to see if it can be resolved by consulting with it.

try to solve it with these possible solutions:
- verify integrity of rimworld files on Steam
- Delete the RimWorld folder from Ludeon Studios
- reinstall mod Prepatcher and verify that it is removed and reinstalled correctly
- When starting rimworld with just core and Prepatcher, even the error remains.


Is the prepatcher dependency really necessary?
