### ISSUE TITLE
Performance Fish causing Stockpile Zones not to work anymore.

### ISSUE THREAD

**Issue by AaronHughes** [bbradson/Performance-Fish#17]
Hi,

So I had an issue with Rimworld for a couple of days, the issue was that I was unable place down Stockpile or Dumping zones on the map, creating the following error: https://pastebin.com/LQ1frVxS

By removing Performance Fish it fixed the issue entirely.

**Comment by bbradson** [comment]
What you've run into here is an incompatibility, most likely even with a mod that already throws errors by itself. It's completely impossible to fix something like this without having the other mod involved in the bug, but your error also points at a method that was seeing fixes in recent updates. Make sure you're having the most recent build from github here, auto-updates don't happen.
If that does nothing I'll need to know the other mod involved to try look into it further.

**Comment by AaronHughes** [comment]
Here is the hugslogs report: https://gist.github.com/HugsLibRecordKeeper/242bd61f3685059285183ccf6ec75ad4

I am using the latest version of Performance Fish normally, inlcuding prepatcher and Fishery. The issue still persists.

**Comment by bbradson** [comment]
I'd need a specific mod there. A log with 437 mods and 100s of unrelated error messages isn't usable. There's been 4 more updates since Prepatcher and Fishery were added as dependencies, too.

**Comment by bbradson** [comment]
Having skimmed over it, the errors looking the most relevant to me seem to be caused by a mod trying to reference Medieval Overhaul, which you don't have loaded. Medieval Overhaul Tweaks might be dependent on it.

**Comment by AaronHughes** [comment]
What would you like me to provide to bring a more detailed viewed of the error itself?

**Comment by AaronHughes** [comment]
Yeah, that seemed to have fixed it. The zoning now works fine with PF back enabled and MOT removed. Thanks for the help.
