### ISSUE TITLE
Room description box apears empty

### ISSUE THREAD

**Issue by YardenDrori** [bbradson/Performance-Fish#23]
I'm not sure what to upload so apologies if I fail to provide some info
hugslib log: https://gist.github.com/HugsLibRecordKeeper/7ae6a3ef6508f72783f162061339862e

When "toggle room display stats" is on the box of room info apears but it is empty and the debug log gets spammed as can be seen with the mentioned log, rebuilding the room does not fix it, when restarting the game it does display it but after a seemingly random amount of time it stops displaying.

**Comment by bbradson** [comment]
That log contains a heavily outdated performance fish version. The throwing line of code has been changed at some point to not at look like it does there for example.  
Keep in mind, github mods like this do not automatically update. If you got the mod from some 3rd party website or even managed to find a reupload on steam, do not use that as they're definitely not maintained by me and obviously outdated

**Comment by YardenDrori** [comment]
yup that did it, I recently came back 2 rimworld from a hiatus and forgot it needed a manual update. thx XD
