### ISSUE TITLE
game lags with repliment

### ISSUE THREAD

**Issue by commanderdarkkirby** [bbradson/Performance-Fish#27]
so this mod here causes the game to lag quite a lot when installed with performance fish and it's dependencies. 
https://steamcommunity.com/sharedfiles/filedetails/?id=1715402900
the lag happens when i build a cadaver processor and the lag only started happening when i installed the more up to date performance fish
https://gist.github.com/HugsLibRecordKeeper/1f6c90fea2f730d069b65c71ea81ec7d

**Comment by bbradson** [comment]
Testing with analyzer shows everything related to the cadaver processor not having any performance hit above 0.1 ms average and not behaving any differently with or without Fish. I would need a lot more data here, but I don't see the connection to Fish in my tests in any case
