### ISSUE TITLE
AllowedToAccept in StorageSettingsPatches brokes storage policies when items changes stats.

### ISSUE THREAD

**Issue by k4m3rn** [bbradson/Performance-Fish#29]
When stats of items changes and became wrong to policy of storage zone, game will not make this item inappropriate to that storage zone.
Example: i had an corpses in stockpile zone, they were fresh, stockpile policy allows only storing fresh corpses, corpse starts to rot, but pawns will never haul it out this stockpile. Another: you make two stockpiles, first can store all items, all quality and HP, second one has higher priority and can store some item, but only with full HP, when item deteriorates and loses one percent of HP, game will not do anything and item still be appropriate to store, that can change if you "touch" storing policy. Turning patch off instantly fixes problem.
I guess better to have an warning at least. 

_(Sorry for my poor language skills, if i did mistakes in text)_

**Comment by bbradson** [comment]
Should be fixed now
