### ISSUE TITLE
Failed to find PerformanceFish.GasDef after upgrading to newest version on 11.03.2024

### ISSUE THREAD

**Issue by ciqasty** [bbradson/Performance-Fish#31]
Hi,

I have performed an update of both PerformanceFish and Fishery on 11.03.2024 and started receiving errors on game load. Sadly hugslib is throwing error 401 during upload of logs so I will try to share as much as possible.
The errors look like this and are thrown for BlindSmoke, ToxGas and RotStink:

```
Failed to find PerformanceFish.GasDef named 'BlindSmoke'. DefDatabase<PerformanceFish.GasDef> contains a total of 0 loaded defs.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
PerformanceFish.Log/Config/<>c:<.cctor>b__12_2 (string)
PerformanceFish.Log:Error (FisheryLib.Pools.PooledStringHandler)
PerformanceFish.Defs.DefDatabasePatches/Replacement`1<PerformanceFish.GasDef>:LogMissingDef (string)
Verse.DefDatabase`1<PerformanceFish.GasDef>:GetNamed (string,bool)
(wrapper dynamic-method) Verse.GenDefDatabase:Verse.GenDefDatabase.GetDef_Patch1 (System.Type,string,bool)
RimWorld.DefOfHelper:BindDefsFor (System.Type)
System.Threading.Tasks.Parallel/<>c__DisplayClass31_0`2<System.Type, object>:<ForEachWorker>b__0 (int)
System.Threading.Tasks.Parallel/<>c__DisplayClass17_0`1<object>:<ForWorker>b__1 ()
System.Threading.Tasks.Task:InnerInvoke ()
System.Threading.Tasks.Task:InnerInvokeWithArg (System.Threading.Tasks.Task)
System.Threading.Tasks.Task/<>c__DisplayClass178_0:<ExecuteSelfReplicating>b__0 (object)
System.Threading.Tasks.Task:InnerInvoke ()
System.Threading.Tasks.Task:Execute ()
System.Threading.Tasks.Task:ExecutionContextCallback (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
System.Threading.Tasks.Task:ExecuteEntry (bool)
System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

```

I have 84 mods. Above errors are thrown between RocketMan prints:
![image](https://github.com/bbradson/Performance-Fish/assets/24845207/6dc1677d-841a-47d6-b18f-80891623c25d)

[Player.log](https://github.com/bbradson/Performance-Fish/files/14562418/Player.log)

The update was performed by removing old version from mods directory and extracting new version into mods.
Anything else I may share to help with resolving the problem?

**Comment by bbradson** [comment]
The gas defs are included in fish's files exactly where they should be: https://github.com/bbradson/Performance-Fish/blob/main/1.4/Defs/GasDefs.xml

Sounds like something went wrong with your download

**Comment by ciqasty** [comment]
Thanks for response - I think I fixed the problem and it was related to Rocketman stats cache?

I have added 2 mods to the list, launched the game and Rocketman detected that mod list changed and reset the cache. No more errors and game loaded fine.

IMO it may be closed.
