### ISSUE TITLE
[1.4] Red Error from FieldInfo.SetValue on compile-time const.  Possibly VEFramework compat issue.

### ISSUE THREAD

**Issue by InsanityPrelude** [bbradson/Performance-Fish#33]
Hi Bradson, I recently got a couple of red errors when running. It's with a fairly extensive mod list, so I'm probably going to pare it back and try to recreate it with less going on. However, I didn't see it all last night on my new save until I reloaded the game and tried it this morning.  

The error appears twice in this relatively short (2500 lines) player.log, starting with "FieldInfo.SetValue has been called on 'public const'", but my in-game log uploader doesn't appear to be working. (As I recall, there's a workaround for this, but I don't currently have it installed.)

[Player.log](https://github.com/bbradson/Performance-Fish/files/14872146/Player.log)
![image](https://github.com/bbradson/Performance-Fish/assets/38642020/e76a4143-d94a-4b3f-ad73-990993918cde)

**Comment by bbradson** [comment]
Fish logs this intentionally when detecting misuse of the method by other mods. This is not going to change and needs to be fixed on VE framework's side instead.
