### ISSUE TITLE
Outdated Harmony mod detected

### ISSUE THREAD

**Issue by bbradson** [bbradson/Performance-Fish#36]
Prepatcher currently includes an outdated copy of harmony compared to what's inside the harmony mod, causing this warning. It's safe to ignore and can be manually fixed by replacing the 0Harmony.dll there with v2.3.3 from the harmony mod

**Comment by Camsinner** [comment]
Could you add more detailed instructions on how to fix this?
I tried to replace the 0Harmony.dll file but it threw horrible amounts of errors when doing so.
I did download the Harmony 2.3.3 package but it has a thin version and a fat version, Plus all of the Net(insertversionhere) folders.

**Comment by bbradson** [comment]
It's harmless and can be ignored. The Harmony mod's Current/Assemblies folder contains the current version Fish is looking for, Prepatcher's Assemblies folder has the older version that instead gets loaded. If you want to get rid of the error, copy 0Harmony.dll from that Current/Assemblies folder into Prepatcher's Assemblies folder, overwriting 1 file, but it's not at all necessary to do that. Zetrith will likely update soon to have it fixed there too

**Comment by quicksilverfox** [comment]
For some reason now only 2 out of 4 hydroponic basin cells are working

**Comment by TonyRettich** [comment]
I also have the same bug as quicksilverfox, but it doesn't seem to affect gameplay at all, only cosmetic.

**Comment by bbradson** [comment]
Looks like Prepatcher now updated, so this shouldn't be an issue anymore. Plant clipping is fixed too
