### ISSUE TITLE
Pawns all invisible including animals

### ISSUE THREAD

**Issue by CloakTheWhat** [bbradson/Performance-Fish#37]
Yeah just as the title says, I recently installed the newest update of Performance fish and now everything's turned invisible, both a loaded saved game and a new game here are the logs

https://gist.github.com/HugsLibRecordKeeper/d1741513ce1b1d697c140ebac7d5a59b

**Comment by StrangeUser** [comment]
Download latest version of fishery library, that should fix, probably.

**Comment by CloakTheWhat** [comment]
Yup that was the issue thanks!
