### ISSUE TITLE
After recent update, pawns and buildings do not render or load.

### ISSUE THREAD

**Issue by Zhakyria** [bbradson/Performance-Fish#41]
After the last update on 4/28, when loading into a save or any new map all of the buildings, and pawns fail to spawn/render. Here is the log: https://gist.github.com/HugsLibRecordKeeper/4d0900c41cac53e4294d7aed973fd036.

When I removed Performance Fish and Fishery, I was able to reload the save and every thing was back in place. This is a test save so there are several wip mods on the list. Before today's update everything was fine aside from the rendering issue with the hydroponics.

**Comment by bbradson** [comment]
That log has two errors thrown for outdated dependencies: https://gist.github.com/HugsLibRecordKeeper/4d0900c41cac53e4294d7aed973fd036#file-output_log-txt-L482
While prepatcher being out of date likely isn't too much of a problem, the outdated fishery version is exactly what's causing the MissingMethodException for the attempt of invoking a newer fishery method
