### ISSUE TITLE
Map fails to load (Nothing but ground, everything else is not there including colonists/animals)

### ISSUE THREAD

**Issue by KillerTheFlareon** [bbradson/Performance-Fish#42]
Only 'mods' used in order:

Prepatcher
Harmony
Fishery
Core
Performance Fish
Royalty
Ideology
Biotech
Anomaly
RimPy Mod Manager Database

[Player.log](https://github.com/bbradson/Performance-Fish/files/15154667/Player.log)

**Comment by bbradson** [comment]
Fishery and Performance Fish are both not updated to the current version in that log, with an error getting logged about outdated Fishery right at the top. Update them and it'll work
