### ISSUE TITLE
Invisible ghoul

### ISSUE THREAD

**Issue by Helixos** [bbradson/Performance-Fish#52]
Hello
I have this that appears when I capture a ghoul and the only thing I recognize is the mod name. This is probably another mod but either way I post this here.

![image_2024-06-03_220613128](https://github.com/bbradson/Performance-Fish/assets/74857074/029af451-f371-4901-b3b2-82add4e71e5c)
Exception drawing 'HoldingSpot382132' at cell (182, 0, 142):
System.NullReferenceException: Object reference not set to an instance of an object
[Ref 67D1A63] Duplicate stacktrace, see ref for original
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch4 (string)
PerformanceFish.Log/Config/<>c:<.cctor>b__12_2 (string)
PerformanceFish.Log:Error (FisheryLib.Pools.PooledStringHandler)
PerformanceFish.Rendering.DynamicDrawManagerPatches/DrawDynamicThingsPatch/Logging:DrawException (Verse.Thing,System.Exception)
PerformanceFish.Rendering.DynamicDrawManagerPatches/DrawDynamicThingsPatch:DrawThingsNow ()
Verse.DynamicDrawManager:DrawDynamicThings ()
Verse.Map:MapUpdate ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.UpdatePlay_Patch5 (Verse.Game)
Verse.Root_Play:Update ()

**Comment by bbradson** [comment]
Has nothing to do with Fish. Duplicate stacktrace means that the full exception got logged in an earlier error. Fish shows up because it added the thing ID and cell to the message. Removing Fish is gonna remove that data, while keeping the ghoul the same

**Comment by Helixos** [comment]
- [ ]
