### ISSUE TITLE
GUI's completely bug out on Linux

### ISSUE THREAD

**Issue by 32bitx64bit** [bbradson/Performance-Fish#7]
No idea why this is happening but it started when I installed Performance-Fish
![Screenshot from 2023-02-14 18-38-40](https://user-images.githubusercontent.com/86190528/218895442-4806d878-7f81-410d-a51f-cdbf9b62f363.png)

Im on Linux 64bit with Performance optimizer and Rocketman installed

**Comment by 32bitx64bit** [comment]
Update - Its a linux compatibility issue. Switching to Proton *uses windows version* worked just fine.

Hopefully y'all can fix Linux compatibility

**Comment by drnfc** [comment]
Wierdly enough, I am on linux and am not using proton.  I have no issues.  I am running Gentoo, but that shouldn't affect anything, usually that just causes wierd issues that nobody else has due to not having a specific use flag enabled.

**Comment by 32bitx64bit** [comment]
Hm weird. Maybe a mod compatibility issue with another mod? 

As my mod list is pretty big (around 80 - 100 mods)

**Comment by 32bitx64bit** [comment]
Switched disro's from Ubuntu Budgie to Linux mint and the issue seems to have vanished... 

No idea why but its just gone. Maybe its because i changed my mod load order
