### ISSUE TITLE
failed to generate an optimized delegate for static System.Void PadMethod

### ISSUE THREAD

**Issue by ezadEzanee** [bbradson/Performance-Fish#8]
Hi, had this error showing up upon restarting PerformanceFish after install. Logs are at https://gist.github.com/af3f6854d64aa97bdaa88652053b91cc

PerformanceFish failed to generate an optimized delegate for static System.Void PadMethod-8a5362b8-c7e9-4b16-b5c4-5b108a380fb8(). Reverting to default behaviour instead.

**Comment by bbradson** [comment]
This is essentially an empty method harmony generates when used on Linux. The new build now ignores these and won't throw anymore.
