### ISSUE TITLE
cannot create "stockpile zones" with this mod installed

### ISSUE THREAD

**Issue by cawphee-black** [bbradson/Performance-Fish#9]
For whatever reason when I have this installed in my mod list I cannot create stockpile zones.
The way this happens is that the ONLY for stockpile zones, the game acts as though it does not see the "mouse release" after the hold and drag.
Basically I select create stockpile zone, the left click + hold + drag, then I let the mouse key go, but nothing happens. If I move the mouse around it acts as though I am still holding the mouse button. 
left clicking just resets the start location for the possible zone but the game still then acts as though I am holding the mouse button down.
right clicking still clears the action so it stops.

The only possible error I see does not come up in the in-game logging if I have dev mode on and pause on error.
The possible error is only visible in the player.log file and is

` GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced. 
(Filename:  Line: 580)`

I tried viewing the logfile live and it doesn't seem like this occurs with the zone creation attempt every time, so I don't know that this error is even involve.

Here is a link to the hugslib log upload

https://gist.github.com/HugsLibRecordKeeper/60302651ef1650c4efd5698bb3165478

And here is my mod list

brrainz.harmony
ludeon.rimworld
bs.performance
ludeon.rimworld.royalty
unlimitedhugs.hugslib
owlchemist.bettervanillamasking
airetexture.core
automatic.bionicicons
dubwise.dubsbadhygiene
dubwise.rimatomics
owlchemist.toggleableoverlays
lwm.deepstorage
spoonshortage.adogsaidanimalprosthetics
spino.megafauna
fluffy.stuffedfloors
dismarzero.vgp.vgpvegetablegarden
dismarzero.vgp.vgpgardenmedicine
dismarzero.vgp.vgpgardenresources
dismarzero.vgp.vgpgardentools
dismarzero.vgp.vgpmoreveggies
dismarzero.vgp.xtratreesandflowers
won.hair
won2.hair
airetexture.mods
brrainz.achtung
gwinnbleidd.anjustquestchance
wexman.advancedhydroponics
crewd.advancedtransportpods
mehni.allyourbase
fluffy.animaltab
oblitus.animalslogic
shinzy.apparello
teok25.archotechexpanded
teok25.archotechexpanded.prosthetics
mlie.archotechplus
fluffy.areaunlocker
pipai.artreroll
flyingstar.automortarsunofficial
tikubonn.autopauseplus
ben.automaticnightowl
nobooms.velcroboy333
fissure.bettergroundtextures
madeline.modmismatchformatter
falconne.bwm
creeper.betterinfocard
mrchimick.blockunwantedminutiae
chippedchap.blueprinttotalstooltip
fluffy.blueprints
powerlunatic.bogbogon
mlie.boommodexpanded
insertkey.buildertweaks
vanya.tools.bulkcarrier
devdisigdu.bulk.components
nerdy.bm
mlie.bulkrecipegenerator
zal.bulksmelting
hol.bsc
brrainz.cameraplus
dubwise.dubsmintmenus
fluffykittens.billcategories
mlie.centralizedclimatecontrol
dhultgren.changecaravanloadout
hatti.cleaningarea
syrus.colonistbaradjuster
fluffy.colonymanager
amch.deconstructpercentage
zylle.confusinganimalnames
xavior.glittertech
3tes.cgtwaa
torann.craftableplasteel
phomor.craftingqualityrebalanced
tammybee.cutplantsbeforebuilding
proxyer.desurgeries.desurgeriescolor
fozzy107.deconstructhfirst
unlimitedhugs.defensivepositions
chv.diagonalwalls
mlie.dismisstrader
tikubonn.dontblockdoor
dracoix.doormat.r12a
arandomkiwi.downforme
telardo.dragselect
kb.dropinventory
oskarpotocki.vanillafactionsexpanded.core
dubwise.dubsappareltweaks
sztorno.dubsbadhygienewtpatch
avilmask.commonsense
dubwise.dubsbreakmod
dubwise.dubsperformanceanalyzer.steam
angryhornet.ed.enhancedoptions
vat.epoeforked
tarojun.epoeforked.removeworkbench
vat.epoeforkedroyalty
etrt.powerusage
zylle.extraalerts
monkey5206.carrycapacityfixed
fuglypump.fallouttraits
spoonshortage.fashionrimsta
jaxe.filtermanager
alex.friendlyfiretweaks
miyamiya.functionalroom.latest
uuugggg.gearupandgo
m00nl1ght.geologicallandforms
albion.goexplore
telefonmast.graphicssettings
avilmask.grazinglands
arandomkiwi.guardsforme
hol.stuffedpower
vanillaexpanded.vtexe
hc.animalreskins.complete2
shakeyourbunny.hdhterrainhtexturehpack
smuffle.harvestorganspostmortem
likeafox.haulexplicitly
jkluch.haultostack
erdelf.minifyeverything
notooshabby.homemover
arandomkiwi.huntforme
murmur.isid
haecriver.injuredcarry
kota.inventorytab
kikohi.jewelry
nestofmoon.jobslimittweak
brrainz.justignoremepassing
kushiyaki.lastvisited
mlie.lessarbitrarysurgery
zhrocks11.letstrade_copy
scorpio.makeanythingcraftable
zylle.mapdesigner
thereallemon.mapreroll
uuugggg.mealsonwheels
notfood.mendandrecycle
unlimitedhugs.allowtool
haplo.miscellaneous.core
haplo.miscellaneous.robots
sixdd.miscrobotshaulurgentlypatch
haplo.miscellaneous.training
alaestor.miscrobots.plusplus
fluffy.worktab
elf.miscrobots.worktab.support
navyseal5.moreharvestdesignators
tidal.morevanilla.textures
paradox.morevanillaturrets
hobtook.mortaraccuracy
thevillageguy.nodropcenterdropraids.1
mlie.noversionwarning
magicalliopleurodon.nonflammablemetal
mehni.numbers
owlchemist.fridgeutilities
vanillaexpanded.vpsycastse
sarg.alphaanimals
vanillaexpanded.vanillaanimalsexpanded
vanillaexpanded.vaecaves
vanillaexpanded.vaeendandext
oskarpotocki.vfe.insectoid
scorpio.optimizationleathers
vanillaexpanded.vcooke
vanillaexpanded.vcef
seohyeon.optimizationmeats
mlie.oreyields
com.rimworld.nales.overcappedaccuracy
fed1splay.pawntargetfix
taranchuk.performanceoptimizer
scherub.planningextended
ltbob.preemptivestrike.rimworld
spdskatr.projectrimfactory_steam
spdskatr.projectrimfactory.drones_steam
prf.materials_steam
aranmaho.prf.retexture_steam
void.charactereditor
edb.preparecarefully
community.psychology.unofficialupdate
dninemfive.qualitycooldown
hatti.qualitybuilder
hatti.qualitysurgeon
ogliss.thewhitecrayon.quarry
sgc.quests
sandy.rpgstyleinventory.avilmask.revamped
ratys.rtfuse
tammybee.raiderinfo
vampiresbane.railsandroadsoftherim
dakkpasserida.animareplant
regrowth.botr.core
regrowth.botr.borealforestexpansion
mlie.roadsoftherim
mlie.regrowthexpandedworldgeneration
regrowth.botr.temperateforestexpansion
regrowth.botr.tundraexpansion
regrowth.botr.swampexpansion
mlie.realfactionguest
lucifer.realisticrooms
twistedpacifist.reasonablecomponents
mlie.recipeicons
kinetictail.reinforcedwalls
fluffy.fluffyrelations
mrgames.removetaintedclothes
reiquard.researchinfo
petetimessix.researchreinvented.steppingstones
fluffy.researchtree
tammybee.restocknotification
kyrun.reunion
brrainz.reversecommands
n7huntsman.rimgunsextended
jaxe.rimhud
rupal.rimpymodmanagerdatabase
orion.hospitality
mlie.rimquest
arandomkiwi.rimsaves
rimsenal.evp
rimsenal.core
match.roofsupport
uuugggg.roomfood
mobius.royaltytweaks
trinity.runtimegcupdated
sf.comfy.meditation
smashphil.srtsexpanded
owlchemist.giddyup
thelastbulletbender.saddleup2
ryder.satisfiedstorage
roolo.searchanddestroy
uuugggg.sharetheload
mlie.simplestockpilepresets
neceros.dws.simpleturrets
owlchemist.wallutilities
petetimessix.simplesidearms_steam
mlie.simplymorebridges
mlie.singleplanttexturepatch
owlchemist.smartfarming
sarg.smartspeed
denev.smartturretcovering
dhultgren.smarterconstruction
legodude17.smartdecon
weilbyte.snapout
marvinkosh.sometimesraidsgowrong
albion.sparklingworlds.full
indeed.stackxxl
zhrocks11.stackablechunks_copy
scherub.stonecuttingextended
vanillaexpanded.varme
crazedmonkey23.armormaterials
windwardsnow.miniturret
ogrecommander.stuffedguns
vanillaexpanded.vwe
oskarpotocki.vanillafactionsexpanded.medievalmodule
vanillaexpanded.vfesecurity
daemon976.stuffedsecurity
sun.reducer
zhrocks11.sunlights_copy
rsev.synergistictraits
uuugggg.tdpack
gt.sam.tilledsoil
owlchemist.toggleablereadouts
smashphil.dropspot
timmyliang.tradehelper
joseasoler.tradingoptions
neronix17.tweaksgalore
dhultgren.useminifiedbuildings
vanillaexpanded.vappe
vanillaexpanded.vaeaccessories
vanillaexpanded.basegeneration
vanillaexpanded.vbookse
vanillaexpanded.vcookestews
vanillaexpanded.vcookesushi
oskarpotocki.vanillaexpanded.royaltypatches
vanillaexpanded.vwel
oskarpotocki.vfe.pirates
vanillaexpanded.vfeart
vanillaexpanded.vfefarming
vanillaexpanded.vfepower
vanillaexpanded.vfepropsanddecor
vanillaexpanded.vbrewe
vanillaexpanded.vbrewecandt
oskarpotocki.vfe.classical
oskarpotocki.vfe.mechanoid
oskarpotocki.vfe.vikings
vanillaexpanded.vfemedical
vanillaexpanded.vfeproduction
vanillaexpanded.vfecore
vanillaexpanded.vtexvariations
farxmai2.vanillafurnitureexpandedpack
vanillaexpanded.vgeneticse
vanillaexpanded.vplantsesucculents
vse.perrypersistent
vanillaexpanded.vanillatraitsexpanded
oskarpotocki.vanillafactionsexpanded.settlersmodule
vanillaexpanded.vwec
vanillaexpanded.vwehw
vanillaexpanded.vweq
vanillaexpanded.vweft
vanillaexpanded.vweg
vanillaexpanded.vwems
vanillaexpanded.vwenl
vanillaexpanded.vwetb
ogliss.toastehs.veinminer
murmur.walllight
bodlosh.weaponstats
deivisis.weightprice
tammybee.whereismyweapon
mehni.pickupandhaul
codeoptimist.jobsofopportunity
zylle.morevanillabiomes
odeum.wmbp
carolusclen.dlc.wmbp.mvb
varisha.extendedinspectdata
papercrane1001.weaponstab
frozensnowfox.bettercamploot
vanillaexpanded.vfespacer
frozensnowfox.efficientutilities
frozensnowfox.filthvanisheswithrainandtime
frozensnowfox.growableambrosia
regrowth.botr.aspenforest
vanillaexpanded.vplantse
frozensnowfox.indoortreefarms
dontstopthemusic.kv.rw
forcedojob.kv.rw
nomaxbills.kv.rw
savestoragesettings.kv.rw
kyd.rapidfireturrets
kittahkhan.grazeup
ryflamer.hdpawntextures
sr.modrimworld.raidextension
syrchalis.harvestyieldpatch
syrchalis.moreslaves
syrchalis.processor.framework
syrchalis.setupcamp
wemd.fastmoisturepumps
wemd.reinforceddoors
mlie.xndprofitableweapons
mlie.xndstuffedflaks
mlie.xndtinytweaks
mungus.xpath.hdiconorgansnpba
krkr.rocketman

**Comment by bbradson** [comment]
That log has over 13k lines of errors that are not related to fish and stops logging messages before fish gets the chance to log anything. You'll have to start at the top, possibly with a more lightweight modlist, and handle errors one by one to get a playable game. Fixing this from my end with the data available there is not possible

**Comment by bbradson** [comment]
Error handling for issues in stats from other mods has been added now.
Regardless, the difference is that it now logs names and affected items of those other mods and doesn't fail at storage creation anymore. Those other mods do still need fixes by their authors.
